# Generated by Django 4.1.13 on 2023-11-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_product_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productSellingPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
